# Generated by Django 4.1.2 on 2022-10-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=10)),
                ('is_chosen', models.BooleanField(default=False)),
            ],
        ),
    ]
