#Using containerized version of Postgres for local development for now.
#We'll using RDS Postgres later
#To start the container run
#docker-compose -f postgres-compose.yml up -d
#To access the Postgres using the terminal run
#docker container ^Cec -it cuol-wordle-backend_db_1 psql -U backend -d cuoldle
version: '3.1'

services:

  db:
    image: postgres:14
    restart: always
      #volumes: 
      #- ./pgdata_testing:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: test
      POSTGRES_DB: cuoldle
