FROM python:3.10-alpine3.15
WORKDIR /usr/src/cuol_wordle
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PORT $PORT
ENV HOST 0.0.0.0
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY . .
EXPOSE 8000
CMD python3 manage.py runserver --noreload 0.0.0.0:$PORT
